version: 2
jobs:
  build-2019:
    docker:
      - image: florentinth/texlive-full:latest
    steps:
      - checkout
      - run:
          name: Copy Files
          command: 'cp -R ./src/* .'
      - run:
          name: Build LaTeX
          command: 'make all'
      - run:
          name: Copy Artifact
          command: |
            mkdir /tmp/artifacts;
            cp main.pdf /tmp/artifacts/;
      - store_artifacts:
          path: /tmp/artifactsversion: 2
